# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "AMP Blog Theme"
license = "MIT"
licenselink = "https://github.com/qtopierw/amp-blog-theme/blob/master/LICENSE"
description = ""
homepage = "https://github.com/qtopierw/amp-blog-theme"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "qtopierw"
  homepage = "https://github.com/qtopierw"
